#: The basic colors

foreground           #F1E6F1
background           #0D050D
selection_foreground  #F1E6F1
selection_background  #3A123A

cursor               #F1E6F1
cursor_text_color     #1E0B1E

url_color             #C58BC5


#: Kitty window border and terminal bell colors

active_border_color   #800080
inactive_border_color #6A356A
bell_border_color     #D06AA8
# visual_bell_color   none


#: OS window titlebar colors

# wayland_titlebar_color system
# macos_titlebar_color   system


#: Tab bar colors

active_tab_foreground   #1E0B1E
active_tab_background   #800080
inactive_tab_foreground #B79AB7
inactive_tab_background #4A214A
# tab_bar_background     none
# tab_bar_margin_color   none


#: Colors for marks (marked text in the terminal)

# mark1_foreground black
# mark1_background #A66FA6
# mark2_foreground black
# mark2_background #D09AC0
# mark3_foreground black
# mark3_background #C46BA8


#: The basic 16 colors

# Black
color0  #321832
color8  #563456

# Red
color1  #C05A88
color9  #D878A0

# Green
color2  #98B88A
color10 #B0D09E

# Yellow
color3  #D2B070
color11 #E5C58A

# Blue
color4  #7FA8C9
color12 #98C1DE

# Magenta
color5  #B98ACB
color13 #CAA2DB

# Cyan
color6  #8BC4C4
color14 #A2DCDC

# White
color7  #E9DCE9
color15 #F1E8F1


#: Extended colors

# You can set the remaining 240 colors as color16 to color255.

color16 #D06A8A
color17 #C878A8
