###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = nautilus --no-desktop -w
$audio_control = pavucontrol -t 3
$browser = brave
#$browser = flatpak run com.brave.Browser --disable-features=WaylandWpColorManagerV1
#$browser = firefox
$menu = wofi -miGI --show drun
#$menu = rofi -show drun
#$menu = walker --modules applications,qalc
$text_editor = flatpak run com.vscodium.codium
$calculator = gnome-calculator
$llm = $browser --app="https://duck.ai"
$vm_manager = virt-manager