#################
### AUTOSTART ###
#################

# Essentials
exec-once = waybar & swaync & hypridle & hyprpaper

# Autostart specific apps in specific workspaces
exec-once = ~/.config/scripts/startup.sh

# Background apps
#exec-once = flatpak run org.openrgb.OpenRGB --startminimized
exec-once = flatpak run com.github.wwmm.easyeffects -w
exec-once = steam -silent -console
exec-once = udiskie

# Visible apps
exec-once = [workspace 5 silent] $browser
exec-once = [workspace 2 silent] spotify
exec-once = [workspace 2 silent] flatpak run dev.vencord.Vesktop
exec-once = [workspace 3 silent] flatpak run md.obsidian.Obsidian
exec-once = [workspace 2 silent] flatpak run com.super_productivity.SuperProductivity