###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = nautilus --no-desktop -w
$audio_control = pavucontrol -t 3
$browser = brave
$private_browser = brave --incognito
$tor_browser = torbrowser-launcher
#$browser = flatpak run com.brave.Browser --disable-features=WaylandWpColorManagerV1
#$browser = firefox
#$menu = wofi -miGI --show drun
$menu = rofi -show drun
#$menu = rofi -show drun
#$menu = walker --modules applications,qalc
$text_editor = zeditor
$text_editor_simple = gnome-text-editor
$calculator = gnome-calculator
$llm = $browser --app="https://duck.ai"
$vm_manager = virt-manager
$rgb_controller = flatpak run org.openrgb.OpenRGB -p

#################
### AUTOSTART ###
#################

# Essentials
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hyprlock
exec-once = waybar & swaync & hypridle & hyprpaper

# Autostart specific apps in specific workspaces
exec-once = ~/.config/scripts/startup.sh

# Visible apps
exec-once = [workspace 5 silent] $browser
exec-once = [workspace 2 silent] flatpak run dev.vencord.Vesktop
exec-once = [workspace 2 silent] spotify
exec-once = [workspace 3 silent] flatpak run md.obsidian.Obsidian

# Background apps
exec-once = flatpak run org.openrgb.OpenRGB --startminimized
exec-once = steam -silent -console
exec-once = udiskie
exec-once = /bin/bash -c "sleep 5 && flatpak run com.github.wwmm.easyeffects -w"
exec-once = /opt/duplicati/duplicati-server
