format = """
[](#3A123A)\
$python\
$username\
[](bg:#551A55 fg:#3A123A)\
$directory\
[](fg:#551A55 bg:#6B216B)\
$git_branch\
$git_status\
[](fg:#6B216B bg:#800080)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#800080 bg:#922B92)\
$docker_context\
[](fg:#922B92 bg:#A43FA4)\
$time\
[ ](fg:#A43FA4)\
"""

command_timeout = 5000

[username]
show_always = true
style_user = "bg:#3A123A"
style_root = "bg:#3A123A"
format = '[$user ]($style)'

[directory]
style = "bg:#551A55"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#800080"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#922B92"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = " "
style = "bg:#800080"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#800080"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#6B216B"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#6B216B"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#800080"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#800080"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#800080"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#800080"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#800080"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#800080"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#3A123A"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#800080"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#A43FA4"
format = '[ $time ]($style)'
