program_options:
  tray: false              # Show tray icon
  notify: true           # Enable notifications
  automount: true        # Enable automatic mounting
  file_manager: nautilus --no-desktop -w # Program to open mounted directories

device_config:
  # Example: Special options for specific devices
  - id_uuid: "your-device-uuid"
    options: [noexec, nodev]
    ignore: false
    automount: false

notifications:
  timeout: 1.5           # Notification timeout in seconds
  device_mounted: 5      # Show mount notifications for 5 seconds